### PR TITLE
Anne-change-the-lesson-title

### PR DESCRIPTION
**Pull request by theredgeek**
Change the lesson title to the one agreed upon.

<details>
<summary><strong>Instructions</strong></summary>

Thanks for contributing! :heart:

If this contribution is for instructor training, please email the link to this contribution to
checkout@carpentries.org so we can record your progress. You've completed your contribution
step for instructor checkout by submitting this contribution!

Keep in mind that **lesson maintainers are volunteers** and it may take them some time to
respond to your contribution. Although not all contributions can be incorporated into the lesson
materials, we appreciate your time and effort to improve the curriculum. If you have any questions
about the lesson maintenance process or would like to volunteer your time as a contribution
reviewer, please contact The Carpentries Team at team@carpentries.org.

You may delete these instructions from your comment.

\- The Carpentries
</details>

### CODE REVIEW

**Comment by theredgeek** [comment]
The 'About' section has a different title, I don't know how (and if I even can) change it but it also needs updating

**Comment by PabRod** [comment]
> The 'About' section has a different title, I don't know how (and if I even can) change it but it also needs updating

This made me realize you didn't have write access to the repository. Now you do, or at least you should have received an invitation.

**Comment by PabRod** [comment]
> The 'About' section has a different title, I don't know how (and if I even can) change it but it also needs updating

Don't worry about this, I'll do it as soon as possible.

**Comment by PabRod** [comment]
After our discussion in person, I'll close this for now. Thanks!

**Pull request closed without merging**
