### PR TITLE
Remove maintenance request, add new maintainers to readme

### PR DESCRIPTION
**Pull request by multimeric**

### CODE REVIEW

**Review by svenvanderburg — APPROVED** [review]
Great! I think in practice Pablo and Lieke won't have time to really commit unfortunately, but if you have direct questions to them you can ping them directly. I would suggest to add them to AUTHORS.

Looking at that, it would also need a change! https://github.com/carpentries-incubator/lesson-R-packaging/blob/main/AUTHORS

**Review by svenvanderburg — APPROVED** [review]
Pablo and Lieke won't have time to really commit to maintaining. But they will answer questions if you directly ping them. I suggest to add them to AUTHORS (which also needs updating anyway)

See https://github.com/carpentries-incubator/lesson-R-packaging/pull/125

**Comment by multimeric** [comment]
> Great! I think in practice Pablo and Lieke won't have time to really commit unfortunately, but if you have direct questions to them you can ping them directly. I would suggest to add them to AUTHORS.

Okay, so should I remove those two?

**Comment by multimeric** [comment]
Alternatively, I'm somewhat inclined to remove the authors list from the readme since it's already duplicating data from the `AUTHORS` file. Thoughts?

**Comment by PabRod** [comment]
My two cents:

- I am ok with removing the authors from the README to avoid duplication.
- I want to keep my collaborators' and my name in the AUTHORS list, regardless of our current involvement.

**Comment by multimeric** [comment]
Yep, you're in the `AUTHORS` file as an author but not a maintainer already.

**Pull request merged**
